#!/bin/bash -e

yum -y update-minimal
yum -y install wget git net-tools bind-utils yum-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct atomic NetworkManager docker-1.13.1

reboot
